name: dawa
description: A new Flutter project.

# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^1.0.0
  flutter_spinkit: ^5.1.0
  cached_network_image: ^3.2.0
  http: ^0.13.3
  shimmer: ^2.0.0
  intl: ^0.17.0
  #clipboard_manager: 0.1.2
  url_launcher: ^6.0.10
  share: ^2.0.4
  package_info: ^2.0.2 
  fabexdateformatter: ^1.0.5
  #flutter_local_notifications: ^1.4.4+2     
  get: 4.3.8
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  animate_do:
  line_icons:
  record:
  audio_waveforms:
  flutter_sound: ^9.1.7
  image_picker:
  dropdown_plus:
    git:
      url: https://github.com/luca-colazzo/dropdown_plus.git
  flutter_linkify: ^5.0.2

 


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-ExtraLight.ttf
        - asset: assets/fonts/Raleway-ExtraBold.ttf
        - asset: assets/fonts/Raleway-Medium.ttf
        - asset: assets/fonts/Raleway-Regular.ttf
        - asset: assets/fonts/Raleway-SemiBold.ttf
        - asset: assets/fonts/Raleway-Thin.ttf
        - asset: assets/fonts/Raleway-Black.ttf
        - asset: assets/fonts/Raleway-Bold.ttf
    - family: Nunito
      fonts:
          - asset: assets/fonts/NunitoSans-Bold.ttf
          - asset: assets/fonts/NunitoSans-Light.ttf
          - asset: assets/fonts/NunitoSans-Regular.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
